branch-defaults:
  master:
    environment: treasure-api-dev
    group_suffix: null
deploy:
  artifact: bundle.zip
environment-defaults:
  treasure-api-dev:
    branch: null
    repository: null
global:
  application_name: treasure-api
  branch: master
  default_ec2_keyname: aws-eb-2
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
